services:
  app_backend:
    image: local_backend:local
    restart: always
    env_file:
      - .env
    depends_on:
      - db
      - redis
  
  app_frontend:
    image: local_frontend:local
    restart: always
    volumes:
      - ./html:/usr/share/nginx/html/static
  
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .env
    volumes:
      - ./mysql-data:/var/lib/postgresql/data/

  redis:
   container_name: redis
   image: redis:alpine

  nginx-proxy:
    image: nginx:1.26-alpine-slim
    container_name: nginx_proxy
    restart: unless-stopped
    depends_on:
      - app_backend
    user: "root"
    volumes:
      - ./local.nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
      - 443:443