all:
  children:
    dev:
      hosts:
        app_host:
          ansible_host: 10.10.10.10
          ansible_connection: ssh
          ansible_user: compose
          ansible_port: 22
          ansible_ssh_private_key_file: app.pem
          docker_compose_dir: /home/compose/app
          ansible_python_interpreter: "/usr/bin/env python3"